title: RundExplorer
home: https://dslej.github.io/rundexplorer/
description: How-Tos/Cheatsheets about Rundeck (https://www.rundeck.com/) and related DevOps things
#bio: 
domain: dslej.github.io
url: https://dslej.github.io
#baseurl: /rundexplorer/
#email: your-email@example.com
#twitter_username: 
github_username:  dslej
reading_time: true

theme: minima
#theme: jekyll-theme-cayman
plugins:
  - jekyll-feed

